### ISSUE TITLE
Release new SAT version (v1.3.0)

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/COMET-Server-Administration-Tool#107]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues) and [closed](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Release a new SAT version.

The new SAT release needs to:
* references the new SDK version from [SDK issue #187](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues/187)
* include all the SAT fixes

**Comment by cozminvelciu** [comment]
SAT v1.3.0 release: https://github.com/RHEAGROUP/COMET-Server-Administration-Tool/releases/tag/1.3.0

**Comment by adrianchivu** [comment]
@cozminvelciu good to go!
