### ISSUE TITLE
Add write retry to server on write failure

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/COMET-Server-Administration-Tool#123]
### Description
As part of the StressGenerator improvements discussed with Ilja, the following improvements must be made:
* [x] sleep interval between each ED generation reduced from a fixed value to Math.Max(0, fixed - elapsed)
* [x] add write retry to server on write failure (static "MaxAttemptsInCaseOfError")

**Comment by samatrhea** [comment]
perhaps the Polly library can be of help https://www.nuget.org/packages/Polly/

**Comment by cozminvelciu** [comment]
> perhaps the Polly library can be of help https://www.nuget.org/packages/Polly/ to do the retrying

@samatrhea Thanks, I'll take a look over it.
